apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: sonarqube-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys and manages SonarQube and dependent database.
  displayName: SonarQube Operator
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAPm3pUWHRSYXcgcHJvZmlsZSB0eXBl
      IGV4aWYAAHja7ZlZkhw5DkT/eYo5AgmuOA4X0GxuMMefh8hUaW21erH+6kpVRlZEJIMEHO4OKtj/
      /nvDf/gpJUsotY+mrUV+ihaVyYcRXz/6vKdYnvfn5873tfT1+fBxQTiVOebXn/19Pk3O189f+PSM
      tL4+H8b7ioz3QOlj4Ocn+5P98/lykpyX1/lU3gOpvT40Hf3Lqa73QPt94zOV92/5mNbr4H+Hr050
      onQqD8oillOOvEt+zyC/fie/ynvKg/tSrnyW3MNzkPdgBOSr5X06xvhlgL4K8qdP4dvof3z6Jvgy
      3+fzN7Fs7xjx4YcXUv3mfP54jHz54PwxI/n6Qprp++W8f+894157rW6WRkTbG1FPsNOnYbhxEfL8
      fK3x6vxWPvfnpbxGnHGT8hN3XLx20iRk5YZU0mEWN9lz3GkzxSImnaPIlvycG7mLys6ep+KvdKWT
      vZMHydpiIWdOy8dc0vNcfZ630+DJJ3GrJAZLnt/feoWfXfwjr3Dv9hClOD5ixbzEkcU0PHP+zl0k
      JN133uoT4E+vd/rjF/gBqmSwPmEeLHDG9Rpi1fQZW/nJc+a+yvFVQin08x6AEPHsymRSJgOxgf7U
      UuwiPSXiOEgQ2BiSiywykGqVwySl5NwkdKFkeDbf6em5V6o08dNwE4moueVObqgvklVKBT+9DDA0
      a66l1tpqryNUrbPlVlptrfXmJDd77qXX3nrvo2ufI48y6mijjzF0TBXNcGDVpl2Hqs4pYfKgyViT
      +ydnlqy8yqqrrb7G0jU38Nll191232PrnkdOPtDEaaefcfRMS8FgCitWrVm3YWrzgrWbb7n1ttvv
      uHrnR9beWf3u9Qeylt5ZkydTfl//yBpnQ++fhkhOJ9VzRsakJDLePQMAWjxncaRSxDPnOYsqFEUV
      Jlk9N+EkzxgpLJak3vSRu8+Z+6W8hTp+KW/ye5kLnrq/I3OB1H2ftx9k7bjO7Sdjryr0mMZM9XHP
      lBH4jZG3v3r8dyCO8/TVbzuz7yhtTa0tj71i3XprLuFIOweWXmDiYG/GJMMiBSXYmtZcSPQerWbF
      HpwyWiqVf+4evjqG+BsXfnisoGhZvgtkAlXgU3bBBtQ9QktnwgLgKN9REw+dK85+U17pDP+u7sx3
      T66AqW1Ep16GuVrrGXm3OmXbWaEbWqdmNkucsxeZckzK3KVKZ71pXaopr37qKnetpEOuJECYa90Q
      MSW9ctMwzz7E6rY4N0+0W0z9plP3ZC5zMuPS523zRFS6QqsyN/juCyYvdRazLUXDqpSyQrp3HD6v
      sqO2UtcoPkLa1/ohR+vkvnua7RgcY70zv9HvOntyR+2ua5SQ6CznDqnzjFKMAjO5WvzarbZQ5oL8
      9a7tKjNRci799nLj8XtOnxbusmTTWE3edzVpw/ZVTTY0FRgMxVYEqfaST9JipWZbu1PzNXlMZA3E
      ae3glsL4NCxeSxUyGMfygEM2duBAgO2KWu79RuXxczeSjNSdRgBzm3XsUc4J8FDO8xA/Mn5Ht3K6
      nJP3XAMjoqkVAn6hpH5s+TSIIBDFz5RbhKVPppt3kMb41urSk7GXuglEXcmcPydcd5gmkcZY8d2c
      L4u5l9w4B95SjuQ6Vz4tNMK7yPro6Xbjzo6xzVSP104mjS3Hc0oBT8yK1VBZsa1tEP+R5ew/DbUJ
      He0Yu4HOlhV2TrcRBCAFLFlfJfCbmtg7d2Z7JZ9KPW4kjofrjKdNAHpwbOmcCZ2qTwZY1HZrT9si
      wQdQHaz3pNM8m6+yQz1+UIfh54VaDe7IFvNiVBMEh/e0qcOGbTdrC7yPeSiR2tTLtWwIJw3XKDBU
      MYgj9eqX5JGQA4ygkruFBJ+l1rae3alOSo08Q2znAQSQT3uDmqJ2yGYRF6OxestGvgVNBLe1jMkp
      VmrT100erEw6qZzCIZSVmkzaEqRWz5JNPB4Yw22EDSDaIH5KGtdGO+/GCRDMCY4pTM3oYw47ksl5
      sjIhKhfHsBSsgp3VqlJfjXLOsA+wm41E9bKpvLhgqsgNT60umhqLjuQ5OjNTbCA1uRDiQk1K8bLp
      8MkxU0QXFl5LjD/LUKhJMAQXO0BDcEKczD2vzAgdMkuwST3JXIuBrnRAt6tONR1YEc2G6xi0ERrN
      UVWhFf4UJJsQMUKDVsoBZ6QZa0M18CiKS71EIc5bz0kHZ5Fqsdl0uc+v8ZDTVfMYG39Eo7dgEYCd
      +HLdqa1q0b2DRIzCAKo0EspNuxBooAPX4DUqIINZKQZok+YYpl7HKpMvSA/RpCgLQYI3s3h574Nv
      axerQrgLMAMxavA01L56h4vghRGoKkbB2FA6lGEmOxgkPDmaZttmHoxxuj8mAiRaHxe33lk8EUBx
      bJCmCSAhGYIwyC+WhjygR/NhuIqSXMA6vEwGJZ4wYZ1cWAZyDvjlTBeJOjoc4MsD158Nn0xOmx69
      CImPJax9Q1fUAZSz4bHkD3IKZQ179/oMdLk0AkoDmVI5fBfSXjL8rifsp7kSbrTNI3KtFq8cHBdc
      4QJiJtRLHy2vgfO3pBpRTEPjJxWBI2S1s9TDLb0WUrBKoynRtncxpHIl4oEXbbjdreSHJOVABJLv
      jlCo2UDlpNAhBiwGqCZ8YKFFqRCDelGlfKiKAXM6a006TdsoNjjCmXb6/sfAYEn/tEUKHycGWCfn
      CkqdRhAzeGMa0s743JEHdeMy2W6m9Ho5mjdondTC3WTtQk8D1V9UvB3O57LXuKiLRVBx17Ma/rkB
      WHNCKLhyyhx6G2JkF9jlE3SA846wNjLGKekUkCMUCsNYMEpLLxVGh5JbjqFleJkdAojb6Q6BNIMb
      6cs80N6yNim5qCDU6PTsZEElcX3Xrkyaqj9r8GW4pULZsGmBbXBTDIRxL9hBiA4yJk4QrUGFmS6s
      GzXajeT5LSwbPwYfUXRLgSeNSxVUkX7FqP4lhxpDfufCFM1TNqyf8IrXSf8tiOgXZ2EMZAy11Lga
      tg9kGgbDJcJCou5ddJ6xV8ZTNcUnFOfDjgFd2S1cQ1PoHxJfVyiZUKRXnYF/ChVGC5VakFrpY06L
      IH5mq7QkQPCiyocIHU/nRF/xxj0n2qOD14BfSDaZlHEaTVdYWDqGiiAXC4Cw5hx9GwsWq5AFMktX
      1BVflRJERgmzYpaEZlPIkMDyR+0UwINupZ8i1SgJtsatHguRhfgjSHV1Tb79tvZAIs6lIBAw+qiF
      /U4ESD2BYTg5yEMOmN+NqSp4jRu9wYPBttZIqGjoYCynJOwmQo7cwo2EnPEo7x1PoMt0o8Ozl6m7
      LoLTUAxYbNOnUb9GxRCQk5BezChgjiywZB10dUg45AVmQq20ih3IkN8NB1NSikAhLUcXZW7b2f1l
      +/Em4/lIZ/3tMfzWhd87Nt9LpEAPjrEPak2MdwM7I1Gn4AM2P6AWx7tZ18JeSC1uu2A5DyAQc/8w
      CANah6HpfcqzNzJx2W4fISyU81GKezpV1fAlPFZJaIbgHYBOeXZTYc0KaAYmmJgU3GsQembf7uS+
      BIVc+uuNMRWnmQafDsP/opfElZCCcvJSI+iDE2AC2Jmb0LmA96I+qrtvyh9+6Is2w1szkjW9zrN5
      Q39SruAI2OJBQNhwpA5F5Vgd3BAWbQzSoM7VF01IkAP+XAWgLJdDxLILZCi0h6UXitkIsld5w5cK
      1wtgMnCElkL8tPawZ0OBqFxG9qYKo0BbB8NGloBcgYoy0aAtF+8A48z5bKZ7cxAUi0aLsL0wlrnG
      NL1Z8ACU1kbYYRnK+Kks+ptNT4D64gux0gv3XJ9eZLsbieK94yObcJBhNrSOLK8+1r3jJNN80X16
      8rWsbFgl6pzuE1fpsyyQv0N4m7nKU+BlHXexCyaBmrANqB+1g+vcAzncKLu6+aQRcprB2xA3NzoY
      rTKeNmEKaaW1RWGUJhtAbdaG5adFa2Ss5w6ltrMf/Zoq4/XBd/mfvv/94a8cF2UfkiLY9NykAF6h
      28Ay0iy5m+y0QKfTnaYYHfgYuKbFvVSnnyrNndRHyaD9xv17szRvcvJsBeVwkWfIl9OjXWzWyDoZ
      x4HETmtHPBb6Ri3kmwhoDhfl7ZhgGNHFbLtXtO2WzpmW0NEc4/SZaRaKkHoD66QbKaHvciflunhn
      OFhygISRjCgy/ubuTANUE6Zyt+aV3fWhruI7rnPEhbh7c2ZIYzSafUqharje2vh+mMG+1YdzG+FO
      C5Rg7vKL4wAiIcB/Cm12nd4bZ1CHmAFahLsEmvuJWGHb3Sv6RgE1Cs9jo2mtsvstceMsbqIVBCDp
      KBgYZwioQOjd6RxHEHzbJFNwMXTg/A/z03eom0kSUR/fQ2Bt/dQjhb9hH4pSnSvQHlQPEA6bRT40
      k59NBtCMYYQXMplBUSN+ldWPyoTTbtGRQAtFV4/duS1opmFwHyFQ7Lq900sc/OaTWBpo+hMvf6KT
      XffTMGdGmKFiNxFtcg1E4ewj4rsSwBPmgVxIqOPQ3IRSaDAJ1d8PGANKshZYWZrG9bpFMvXU8aQy
      gOVxhIbrxkOeaQELBhqP3F1MDOdnqDvsnQaLic3wtMlrH2wwb7iEBgbnFiIMs5m0IB00jdDi7lQe
      9EWUrnfRzhURqliQOVNh8Et7g4bFCE8LXRbgSUGXuYOG3u+ZTwkAAWDMnxjNiUsV7DMPaUJXRAhc
      1B/dhZbkc38ffn2n7ufHbwd6tr4WxAbxuddMNM8FXxI3K8XPkK2GStJCFtBaoEaYA3luISEzqBHt
      AA0ZhV/gaP8OtVB9k0fMO2P4AYhHX1myi1XslhFA8khquZcWQiri4uV9u7t217J7LgXvLlzJGbJy
      UMozXhtlF5yS8CpTC4QNbJTOxF5bGu4PcNfNN5raku3ez0WqSib3j4IZ+j8bJqfSQkCEhN1lIOHl
      aLqp4uB7ZXW7z6JwOvaAxEa0fxQ0pnoP8Copb6v/ud1j55vkm/H0PDqauRPHmiL6kNm9p1aQhYE1
      bzJN0mDOblbwS4TW+evEQEdFd/BsfMoV2WBbGypmiS8jEoAVgrxuELUk10eKTrg2K/236+jErXZm
      RFBSoh3FKxQ4QGlIMeXF92DVc4tL+ed32J1uqVa6ufqgBcpm/jgzx0v07eo8YKW0x2PbcKBYyIZl
      NHeK9PKmEqBD79ayg02xCYeepanbuISxoycB7zh2HBZf901sXOQ5MbnNSA3KWSlOsB3o1mn53LBF
      xJPG50/2yeGvRMYo3OXb1lhkjBbERv2Ujeo32QVLTh1Ur6TtE/O+Bicw+7NPKB4S/4+rSfc1Sm7w
      Jt2gUCIk+6Kx/v8PgqXzH+wY9PzeDAAPv+Jvwvg7DNK/A/36QDCFhv8D6WsKkz5fmoQAAAGEaUND
      UElDQyBwcm9maWxlAAB4nH2RPUjDQBzFX1ulKhVBO6g4ZKhOFqSKOGoVilAh1AqtOphc+gVNGpIU
      F0fBteDgx2LVwcVZVwdXQRD8AHFydFJ0kRL/lxRaxHhw3I939x537wB/vcxUs2MCUDXLSCXiQia7
      KgRf0Y1+DGAIMYmZ+pwoJuE5vu7h4+tdlGd5n/tz9Co5kwE+gXiW6YZFvEE8vWnpnPeJw6woKcTn
      xOMGXZD4keuyy2+cCw77eWbYSKfmicPEQqGN5TZmRUMlniKOKKpG+f6MywrnLc5qucqa9+QvDOW0
      lWWu0xxBAotYgggBMqoooQwLUVo1UkykaD/u4R92/CK5ZHKVwMixgApUSI4f/A9+d2vmJ2NuUigO
      dL7Y9scoENwFGjXb/j627cYJEHgGrrSWv1IHZj5Jr7W0yBHQtw1cXLc0eQ+43AEGn3TJkBwpQNOf
      zwPvZ/RNWWDgFuhZc3tr7uP0AUhTV8kb4OAQGCtQ9rrHu7vae/v3TLO/H5hmcrbZhnP3AAAABmJL
      R0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5AkSExsXgoRdJQAAGs1J
      REFUeNrt3Xl0HNWBLvDvVq/qbi2tXWrtsmRJNrYxNjZ2MNiyDTYmQCAsM/POmzAJZEKAAWJCCPNw
      QjIQPEk4LyEZwptkErIQYAAHYzCLzWaDN7zbWixrs9bW2uqW1FvV+8Nw3nlJd3VLXS2rpe93DnA4
      XVKVquuru9Ste4WiKAqIaEaTeAqIGHQiYtCJiEEnIgadiBh0ImLQiYhBJyIGnYhBJyIGnYgYdCJi
      0ImIQSciBp2IGHQiYtCJGHQiYtCJiEEnIgadiBh0ImLQiYhBJyIGnYhBJyIGnYgYdCJi0ImIQSci
      Bp2IGHQiYtCJiEEnYtCJiEEnIgadiBh0ImLQiYhBJyIGnYgYdCIGnYgYdKJJO901AkXheWDQacZy
      e4N4dGcTvv3KKbT1j/KEXABCUXifpfjaurMRH7WPAACCCnDzvEzcuqwARh3LGQadwpIVQBKJcawn
      Olx4+I0z+OvDzbIY8K3VxajKS+EXyqDTX3O6vfjHP5/C2qJkLC1Ow0WFaUhN0k/LY1UU4BvPH0en
      xx/yc7+i4NZ5WSzdGXT6a68e7sSvD3VDfBYkr6xgQbYFG+emY36RHVk247Q51m6XF5u31cHlDapu
      l2M14KHaUpRl2/gFM+gEAD/YXocD3X/boaUA8MkK5mdZcF11BhYUp0+Lkt4fVPDyoQ48d6wXOpXt
      AoqCu5blY+OCPH7JDPrspijALb89Am9AjrhtQAE2VdhRW5WJytzkC37sLX2j+MUHLajrH4cQ4f++
      5Q4b7qktg82k5xfOoM9OxzpceHjHGegm0BEnK0CmxYCvLs3F/EL7BS/lXznUgV8f7lF9rptm0uF7
      G+agJNPKL51Bn32e2X0WO5qGJv3zMoCNlenYUJN1QUN0pteDn+46i3Nuv+p2D1xehFVzM/nFM+iz
      qNoO4Nn3W7Dz7BC8AXlCpXqo31WRkYR/XlGA8pxkXIgndf6gjGc/aMHrZwahD1OXVwCsK7fjzlUl
      MOoELwIGfXYFfn/zIA409eOTLg+GxoMxhT7HZsT9q4pQkZcMnZj6MO1rGsCPP2xT7XfItxnw2KZK
      ZNpMvAAY9NnpZOcIPqxz4mC3B90e/6RDn2rW48ErizE3LwWGKS49Bzx+bN3ZiJMD42FrFyadwJOb
      KlGSxXY7gz7LS/ozvR5s+7QTB7o9GAvIk6qSW40SvnVFMS4qSJvywD/3STtePOEMe9w6IfDoulIs
      LErjF86g/z/u8cD5P1Kc/9dn/4GAgE4SU34hT2X7982TvXinrg/NLt+kAp+RpMfDa8tQlm2FNIVV
      +oPNA3hidyv8cujLUgjgG8sdWFeTA8FmO4MOAF//wzH0fzYq6/OLQnz+jxAwSUBWigmOVDMcqWYU
      pJlRmGaCzaSHThLQ6yTodVLC3hBkRUFr/xh+u6cVx/rHEZQn9lULANVZFjxQWzql7WOny4tv/6Ue
      /Z/dqEP5YnUmvrKicEpvQgz6NPXV547CGWH4ZbhSQycEDELAIAFJegkF6Ukoz7BgUUEyiuxJ0Osk
      GPUSdAnwdokCYNQbwHP7zmFPyzBcvomdE50QWFuehttXFsFs0E3JMXu8QWzZXoeGQW/YbVaVpOG+
      2lKGnUGfXNAjkQRg0kmw6AQK0sxYUJCCFSV22K2GaR9+X0DGu/V9eOVoN3pGAxP6WbNO4PalDqyp
      zoRhCl5CCcgKfvpOEz5qc4Xd5uI8Gx7ZUAG9xLAz6FPErJOQZpRQk2fDmrmZqMi2nq/+T8OLMBBU
      8Gn7MJ7d04besYkFPseix3fWl6Mk0xr3Z/CKArxypAu/+7Qr7Aw1VRlJeOyLc/kGHIN+YRgkgXST
      DlU5Vmy6KAelmRboJWladSL5gzIOtA7h2T3tGJjAuZIEsLIgGffUlsOoj2/AFAAnzrnwvbeawnbS
      laeZ8Pj11TDpGXYG/QK3k60GCQVWAy4ts2N9dTZsJt20qeb7AjLerevDfx3owHgw+kvCZpDwteUF
      uKIyM+43sBanG5u3N8IX5vjKPgu7mWFn0KeTPKsBi/JtuG5RHnJSTNOiU2nUF8Tz+89he30/JpB3
      XJJtweYNlUgyxDdknYNjuG9bPcbDjKQrSTHiiRuqkTRFnYYMOoM+odI+z2rAojwrNi7IQ6HdfMFD
      7xr146ndzfi0y41oLxCLQcLXljuwZm5WXI/NOeLFvS+fhscfLuwm/OhLLNlnTdB7BscwFpDhC8jw
      BmX4ggp8n/2/0+NHt9uL7hEfekd86P9suiMZChQFuFAnRQZQYDNgVWkablrimJLebbUbUIvTgx++
      cxZOjz/qn1tdnIK71pTF9dj73V7c+3IdRsI8KqzJTMIPr6vio7fZEPTJtFO9ARnj/iD8/iA83gBO
      O0fR6BxFg3MUPW7flN0AFACSELgsz4qrF+RiYcGFm0TRH1TwYYMTT+05F3Uve0GyEVs2VCArJX4D
      bQbcXtz7Svipqi7Nt+G7Gyt5YTPoEzPul+Ea88Mz7sfJbjf2tbtwvMsNGYjrY6agAjhsBqyvSMem
      RXkXrGe53+3Dk++eRZ0zurnZJUngnpUFWB3HqvyAx4f7XqnDUIhRdAqAq8rtuGt1KYPOoMdY8irn
      24xDbi8+aR3GruYh9Hn8kIT24VcAGHQC186x44uLHUi3Gqa+aaEo+PjMAJ54rzWqKadlBbi2wo7b
      V5XEbTzBoMeHe14+HbJklxXgHxZm45ZLCxh0xlVbw2MBOF1jOHpuBH+p60P/qF/zd70DCrC+JAXX
      LspD2QV4dbPf7cNTu5txrMcT1fbVGUn49lVzYLfE5+bUNTSGu1+thz9Eb3xQAe5f6cCamhwGneKn
      x+VF54AHu84M4r2WYUDDBRj8soLL8m24eUk+5k7xJJCyAuxt7MOPPmiLam0vg17ClnVlmO+IT39D
      s9ONe7Y1hDwWBcCjtSW4pDSdQaf48wcVnOkZwb7mIWyr70cgqGgSer+sYKUjGTcvyUdFztTOj949
      PI7H3mrCuWFvFDURBV9bkofrL86Py7Ecbx/GQ282QR/inOokga3XVqJ8Fk5ewaBfQEEFaOhy4WDL
      ELY1DMDrl2MOvV9WcHlhCm6+JB/l2VN3QcuKgpcOdOD3x3oj9k0oClBbkoI7ryyDOQ4DbD5o6MOP
      3m8NORddhlmP//3lebCZdAw6TT1ZAY60DeHd+j7sahmGQRIxdeYFZAXry+24dakDOSlT9y75oZZB
      PL6rJeyY9P+v3Z5uxnc2VMZlCuoXDpzD74/0hhyWW5NhxuM31DDodGG5xgPY19iHbXX9aBkaj6kj
      TwbwT4tzcPWCvCkbKdbv9mHLjka0urwRb1b2JD22Xjs3Ls/bf7HrLHaeHQrZXr++KgO3f6GYQafp
      4USHC68d68ZH59wh253RMuoENq8qwtLyjCmZ3llRgGfeb8brjYMRmyNGvYQfb6pEUaZF02MIyAq+
      v70eR3tDL2H1r7UlWDpLOucY9ATRNjCG7Ue68ObZoUkHVQHgSDbiodoyFGscqnDePtGNp/d1IuJV
      JgS2bpyDyjxtnxwMj/nxjRdPwR1iqKxZL+HnN1YjK9nEoNP0MjwWwLZDHdjWOAB/UJl06G9bkI0b
      FudPySi7010jeOLtsxiKMIWVDOB760qxuNiu6f7b+z2465X6kOcq36rHz26eD/0Mn7SCQU9Qo74g
      XjpwDtsbBzE+yamdkwwSvn9VOSpy479ay9CoH4+8Vo/2EZ962BXgwSuKcHmltksx7T87gB/sagn5
      d9aW2XH36tIZPausbsuWLVsYm8Rj0ElYWJSGa+ZlQfEF0DLkRWCCs7wGZAVvNwygc2AUCxwpcZ0p
      xmzQobYqE8fbh+AcC4S9sQgB7GkZRlaSTtMRfw57EtweHxr6x/7ms5bBcVRlmpGXlsQSnaa3cb+M
      5z5uw44zg5DliX+leiHw+DVz4l66ywrw+JsN2NfhVt2PAuDuFQVYV5Ot2b59QRn/8uIpdLj/tlaR
      pJfwzC3zkJpkYNBp+hvw+PCL95pxoMsz8YsBwI3zMnHrpQVxfw/+6d3N2Nk0GPGm8k2Nw9434sWd
      L54KWfupSDfjyRuqZ+Q77Ky6zzBJRh0ur8zEZUWpaOh0YcAbnFAJfco5infq+7C8OBU2c/zWUr+0
      1I6A14+TzlHV4zvQ7kJRigmF6dpUqy0mPcrtZnwY4vn6wFgABclGFGdYGHRKgGoagDSLAetrsuBI
      NuJY50hUI9U+NxaQ8cbpPmSapfNTOsephFtYmAqLUHC4y6263cetQ6jOsiA31azJfvPTktDU40ZH
      iI7Bg+0u1Fakw2LUz6xrglX3mc89HsATOxtx3Dk28ZLXkYzN6+I7pfPrR7vwqwNd6n0IksCPrqnA
      HI1e2HF7A7jj+RMh550rTTXhJzfVzKgqPIM+SygK8GnrIH7yfivcfnlCP2s36/DYNZUotMenV1oB
      8Maxbjyzv1N1O5NO4Oc3ViM7RZuSvb5rBN/e0RhyMM8ja0qwtGzmjJrjNJmzpTovgEtK7PjVrfOx
      OHdiK6wMjgdx3yt1ePtUL+JRLAgAGxbk4o6learbeYMKHni1HiNjfk32W5mXjBWFod+Nf/K9Vgxr
      tB+20WnKGfUSrqjIRHm6CfvbhqOeu11WgP3tLvQPjWJJqV3zdrsAUJGbDCkQxHGVWWu8QQX7zg6i
      tioz5tFsAsDiwlS8dboP3r86EUEF6HN5saJ8ZpTqLNFnael+aWk6nr1lPuakTWyc91vNw3jkL/UI
      BLUv2gWALy91YP0c9XB1ePz44Y6GCS8DHUqSUYeHaktD1nA+bB1Gs9PDoFNiS7UY8OSXanD70ryo
      q/ICwEnnKO558SRc49pXbSUh8PVVxVicr/5yyzHnGH6zt02Tfdbkp2BBduhHaj94q2nCIw4ZdJp+
      bTdJ4LqFeXj6xmokG6OfdaXD7cNdL5xCS/9oXI7p4avKUZBiVN3utbp+fNjQp0kN58H1c2AJMdtN
      31gAexv7GXSaGRz2JDxzyzwsz4/+8ZXLF8TmbfU42Dqk+fEYdBK2Xl+N1Ag3n3//oE2T6rXNrMdt
      i3JDfvbTPe0YHPUz6DQzWE16PLShEl9f7kC0tVWfrOCH7zTjvXqn5sdjMerw1I3VMOvUGxYPvd6I
      IQ2CuOmiHDhCzJUvywpePdzJoNPMIQSwYX4OfnbD3KjfVZcVBU991I43j/dofjzpViO2fnGu6uIP
      4wEZW986E3NbWpIE7r6yJOSyWy+d6kPX8DiDTjNLSaYV//HlGuQlG6PaXlGAX+7rwKuHOjRfn64o
      w4KHrixW7TA80TeG5/e1x7yvqtxkLA7RMacXAi8e7GTQaeZJtxrx4xuqsTgn+vfCf3O4By/sa9d8
      YM2S0nT83UL1t9ieP9GH4+3DMddovrG6NOR6WjubBtHS52HQaQa22406PLyxEtfMSYu6pP7jcSde
      2K9t2IUAblriwLys8G+W6QSw5Z2zMbfXs5NNWBVi9Vq9JPD7/R0MOs1MBp3A164sw/9YmB11J90f
      jzvx6qfahkISAo9urESmOXxPfCCo4D/eb455X1+5vBhSiH6BjztG0NA9wqDTzHR+1FoB7lyaF3XY
      /+twD3Yc7dL0OEwGCd/fNBdGlZ74vefceOdUb2zNFosB60tTQ7bV/5iAbXUGnSZk06I8/MvKgqjH
      yD9zoAtvn9C2N96RZsbdKwrCNiWEAJ7aew49Lm9M+/mHy4pC9vYf6HKjrmuEQaeZrbYmG4/UlkQd
      9p990oG9jX2aHsOquVn4QmH4YbI6AD/b3RzTE4Bksx7XVtpD9AUIvHqsm0GnmW95WTqe2FgedbX/
      8ffacKrTpekx3L+2HLmW8DPBHHOOYvuR2JoONy0tgP6zZoKsAOlJety5NA/3r52TWE0vTjxBsTje
      4cIjb5yJalsZwDM3VSNfw2mVG3s9+NZr9QhXdAcU4De3zkN2DKux/PHjNuxpc+FLC7Kxuipbs7Xt
      GXRKKEfbh/HoW01RPU4z6iX8+pZ5SNZwWuU/7G3Dn0/1hR1Qc2meFd+9Zu6kf78vqKh2/rHqTrPC
      wsJU/K915VGVdL6AjAdfa4A3IGu2/79fUYQilRF8n3R68EEMb7klesgZdNLM4qJUfLe2FNFkotPl
      xdO7z0LL17zvXV0StuNNEsAvP+nQ9ObCoNOstaTEjq9e6ohqEov3W114XcM3wiqybbi5JiNs2Ed9
      QfzuoxYGnUgLG+bn4JqK6FZD/dWhbhxqGdRs37ctL0K6yqITfzkzhO4Yn60z6EQ4P1jln1aVYFkU
      E1hIAnjs3Wb0jmgTPp0kcO/lRWGbBBKAX+w+i9nY/cygk/YXlRDYfNUclEUx8aSiAP/6eiP8QW3a
      zxcXp2FtWWrYz484x7CnaYBBJ9KCQSfh8euqkBbF+m3dbh9+ubtZs33//bJChLttCAB/ONihyQyy
      DDoRzq+J/oNrKqCLYg74d1qGNRsTn2kz4o5LcsN+3uH2442TPQw6kVYK7Un45sqCiGPOBYBf7uvU
      bLqmqxfkwmyQwu7rpaM9cZmbnkGnWWtNVRaunxt5xZOgouDfdp7RpLPMoJPwwBcKw95gBsaDePFQ
      B4NOpKX/ubIYS3Iirzve6vLh/3ygTXt9aVkGHGHmhhcA3qjr16wTkEEnwvlHXw9cVQFLhHnaBYDX
      GgdxSIO54oUAvrmyMGwNYdgXxPZjPQw6kZYsRh0eqS1FIELdXAB4+sM2TZZCmudIxXyVmsS2E72z
      olRn0GlKzXOk4O/mZ0Xcrn88gGfea9Zk6uivLHOE/T2D3iB21fcx6ERau2VZIeakmyNu93bzEOo1
      mIixIicZlRnh34H/86ddM75UZ9BpyuklgQfXliMYYTtFAX6yq1mTwS1fX1GgUnsI4ug5F4NOpLWc
      FBPuWe6IWDXvGQ3gtxosj1yenQxHSvghub/a0zYjlkdm0GnaWTc/B/OzIk8rtaNhAP1uX0z7EgK4
      e2Vh2M97RwPoGBxj0Im0JgDcc2UpAhEKUr+s4Mm3myDHOJJmTm4yksKMllMAPLunjUEniofcVDO+
      uSw/4nZ1/WM41Rlbx5xBJ3D/5UXh99E3Bvd4gEEniof183NQEsUrrVvfbY65d3yeIyXs3HZ+WZmx
      j9oYdLrgdJLAfVeURJxDbsgXxI4YF06wmvTYVJUZ9vM/zdBHbQw6TQslWVZcXZ4Wcbs/HOmJuXp9
      3YLwc7OPyQr6RrwMOlG83LYs8uus3qCCPx2M7a2zjGQzHLbQL7soCvCng10MOlG8pFuNuGNp5I65
      nQ0DGI5hDXQB4KuXhR9As7dtGB5vkEEnipe1NdmwRXjDzS8r+P2B2Er1ihwbTGEmoffLCnqGRhl0
      ongxGyRsvrI44nbvnhmMaRCN1aTHxfnhV2P9zYFOBp0onuY7UmE3q5fqQUXB7/afi2k/X1kWfrGJ
      Ez0euGbQM3UGnaYdvU7goTWlEbf7oHkoplLdbjPBGmaknKwA3YOjDDpRPFXkJiPboj5VtKwAO070
      TnofJr2ESwpSwn7+p8M9DDpRPOkkge+sLYu4jtvLJ3tjqmLfujgv7D4Od45g1Bdk0IniqTjLiqwo
      SvWDzZNfeSUj2QSbyosufa5xBp0orqW6ENgcRVv96Y874JvkksgmvYTKzPBzyu1tHmLQieKtNMsG
      u0m9Bz4gKzjdMfkZYm5YFH5Vl22nnAw6UbwZdAJ3faEo4nY/39s+6X1UZFuRpA8dBY9fRs8MWGqZ
      Qadpb2FhKlIjjJbrcfvR2ueZZPVdh7wwfQECQOeAh0EnijejXsKtF+eqbiME8Pbpyb1LLgRwpcqr
      q9tP9zPoRFNhTVVm2Or1516t78fwJB+11VZmQgqz6uvhLjf8Cb4go56XECUCk0GHi3Ks2N8Rfjop
      HYCTbUNYUZk54d9vNuqQZdaheyyAojQTVpelY3FBMlKsRqRbjIhi5edpTSiKovAyokTQ6/LijhdO
      qr6znmk14D9vu2hSv79raBwpFgOsEfoDWHUniqMMmxH5EQbQ9Lh9aOmb3Bj1vDTzjAw5g04JRScJ
      bLwoR30bIXC0bZAni0GnRHZ1TVbETrmXTvXzRDHolNiluoQ5aUbVbQbH/GjsdfNkMeiUqIQANi7I
      U+2Q0wmBoy1DPFkMOiWyZSVpYSeM+Nx/17H6zqBTYl+0ksC8DPXFGV3jATQ5PTxZDDolbPUdwIaL
      clRXdtFLAo0dLp4sBp0S2cVFqbAZ1S/f91qGeaIYdEroUl0IVNnNqtsc6fXA7QvyZDHolMjV90VF
      aaq97wYhcKyVve8MOiW01VWZqkGXBHDsHKvvDDoltGSTHsUp6oNn9nZy4AyDTgneTgcWZltUt3F6
      /OiNYZEHBp1oGlhYmq7+mE0I1PExG4NOie3iwlSorfIgCaCpZ4RB56VCicwgCZSmmlS3OdwzyqDz
      UqFEV5Ou/jy9cXB80gs8MOhE08Sc/BTVdrpOCBzvHGHQiRLZ4qI0BFWmPpQE0O50M+hEiSzdakB6
      Uvi55ASA9sExBp0o0ZVF6JA7M+Rl0IkSvp1uVw96y7CPQSdKdPkZVtUOOX9QntXVdwadZkbVPdum
      2iGnEwKNPW4GnSiRlWRYoJPCD5GTBNDNEp0owS9kAeTZ1N9k65/FL7cw6DRz2uk2g+rnXR4/g06U
      6AoilOi9owEGnSjRZUUo0fvGGXSihJeWbFZ9xOYLyBgc8zPoRAldoqeaIUNtzLtA+8A4g06UyLKT
      TaolugAwMOpj0IkSuuqepEdQLegCGPYw6EQJTS8JmFXWThcAXCzRiWZAqW7WqX4+ys44osRnN+lV
      Px/xyQw6UcIHPUKJPuKXVVd3YdCJEqLqrl6ij/pZohMlPJtB/ZL2BhXMxiKdQacZxRIp6DJLdKKE
      ZzWot9F9QYVBJ0p0Rr1QD7rMoBMlPL1ep9oE98/SEl3PS4NmErNRhxS9BBGmYBdCzMrzIhRFUXh5
      ELHqTkQMOhEx6ETEoBMRg05EDDoRMehExKATMehExKATEYNORAw6ETHoRMSgExGDTkQMOhGDTkQM
      OhEx6ETEoBMRg05EDDoRMehExKATMehExKATEYNORAw6ETHoRMSgExGDTkQMOhEx6EQMOhEx6ETE
      oBMRg05EDDoRMehExKATEYNOxKATEYNORAw6ETHoRMSgExGDTkQMOhEx6EQMOhEx6ETEoBMRg05E
      DDoRMehExKATEYNORAw60ezwfwGJT18Vm6MPawAAAABJRU5ErkJggg==
    mediatype: "image/png"
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redhatgov
  - sonarqube
  - devsecops
  links:
  - name: SonarQube
    url: https://www.sonarqube.org
  - name: SonarQube Operator
    url: https://github.com/jharmison-redhat/sonarqube-operator
  maintainers:
  - email: jharmison@redhat.com
    name: James Harmison
  maturity: alpha
  provider:
    name: RedHatGov
    url: redhatgov.io
  version: 0.0.0
